include:
    - local: '/tools/ci/shared.gitlab-ci.yml'

variables:
    PACKAGE_NAME: '@rr-internal/rr-button'

stages:
    - build

build_if_tagged:
    extends: .base_build
    image: node:18.15.0-alpine3.17
    rules:
        - changes:
              - packages/ngx-iframe/**/*
          variables:
              CHANGES: 'true'
        - when: always
    script:
        - !reference [.base_build_scripts, check_tags]

        - sed -i '/^use-node-version=/d' ./.npmrc ./packages/ngx-iframe/.npmrc
        - cd ./packages/ngx-iframe

        - npm install --global pnpm@8.2.0

        - pnpm install
        - pnpm exec ng-packagr -p ./projects/rr-button/ng-package.json

        - cp .npmrc ./dist/rr-button/.npmrc
        - RUST_LOG=debug ../../tools/ci/scripts/set-version-from-tag --output="../../package-version.env" --package="./dist/rr-button"

        - cd ./dist/rr-button
        - pnpm publish --no-git-checks
        - cd ../../../../

        - !reference [.base_build_scripts, clear_tags]
