name: CI

on:
    push:
        branches: [main]

env:
    REPO_API_TOKEN: ${{ secrets.REPO_API_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [18.15.0]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: cd packages/angular/ngx-iframe
            - run: npm i -g pnpm@8.3.0
            - run: pnpm exec ng build @rr-internal/ngx-iframe-parent
            - run: pnpm exec ng build @rr-internal/ngx-iframe-child
            - run: cd ./dist/ngx-iframe-parent
            - run: pnpm publish
            - run: cd ../ngx-iframe-child
            - run: pnpm publish
