name: Push ts-imports
on: [push]
env:
    REPO_API_TOKEN: ${{ secrets.REPO_API_TOKEN }}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: npm i
            - run: npx rr all.run -c=build
