name: CI

on:
    push:
        branches: [main]

env:
    REPO_API_TOKEN: ${{ secrets.REPO_API_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: [18.15.0]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            # <ngx-iframe>
            - run: sed -i '/^use-node-version=/d' ./.npmrc ./packages/angular/ngx-iframe/.npmrc
            - run: npm i -g pnpm@8.3.0
              working-directory: ./packages/angular/ngx-iframe
            - run: pnpm install --filter="ngx-iframe-workspace"
              working-directory: ./packages/angular/ngx-iframe
            - run: pnpm install rpc-chan@0.0.3
              working-directory: ./packages/angular/ngx-iframe
            - run: pnpm exec ng build ngx-iframe-parent
              working-directory: ./packages/angular/ngx-iframe
            - run: pnpm exec ng build ngx-iframe-child
              working-directory: ./packages/angular/ngx-iframe
            - run: pnpm publish
              working-directory: ./packages/angular/ngx-iframe/dist/ngx-iframe-parent
            - run: pnpm publish
              working-directory: ./packages/angular/ngx-iframe/dist/ngx-iframe-child
            # </ngx-iframe>